manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cdc-mkb/zmk
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-pim447
      import: app/west.yml
  self:
    path: config
