manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/mmawdsley
  projects:
    - name: zmk
      remote: mmawdsley
      revision: eb8889883d1e91f58a42f0babc17a10fa3fa1b4a
      import: app/west.yml
  self:
    path: config
